version: "2.4"

services:
  odoo:
    build:
      context: ./odoo
      args:
        DB_VERSION: "15"
        ODOO_VERSION: "16.0"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    environment:
      EMAIL_FROM: ""
      PGDATABASE: &dbname prod
      PGUSER: &dbuser "odoo"
      PROXY_MODE: "false"
      LIST_DB: "false"
    tty: true
    volumes:
      - filestore:/var/lib/odoo:z

  db:
    image: ghcr.io/tecnativa/postgres-autoconf:15-alpine
    shm_size: 4gb
    environment:
      POSTGRES_DB: *dbname
      POSTGRES_USER: *dbuser
      CONF_EXTRA: |
        work_mem = 512MB
        lock_timeout = 5s
        statement_timeout = 30s
        log_lock_waits = on
    volumes:
      - db:/var/lib/postgresql/data:z

  smtpfake:
    image: docker.io/mailhog/mailhog
